### ISSUE TITLE
Windows bug - it looks like when I run main.py it blocks after minima step

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonsegpy#21]
![image](https://cloud.githubusercontent.com/assets/14980394/24870246/b322b62a-1de3-11e7-8dee-f7dab41d841f.png)

This is the same bug as last week.

**Comment by alzaia** [comment]
![image](https://cloud.githubusercontent.com/assets/14980394/24870515/89022d52-1de4-11e7-9812-e4df48183fc5.png)

**Comment by Aymendje** [comment]
Same issue as #22 
It should be repaired now.
