### ISSUE TITLE
test.json file - INVALID

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonsegpy#22]
main.py cannot run without errors, check your test.json configuration file, the inputs and outputs are not correct

![image](https://cloud.githubusercontent.com/assets/14980394/24871314/335b67d0-1de7-11e7-83d7-4ae4f563cf40.png)

**Comment by alzaia** [comment]
Obviously, this problem is independent of the platform. We tested it on both Windows and Linux.

**Comment by Aymendje** [comment]
Please retry
It was the wrong  test.json
