### ISSUE TITLE
Axon-myelin display in mask

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonsegpy#24]
As discussed last week, we said we wanted a final display similar to the current AxonSeg version (as_display_label() function). You should be able to close the outer myelin shapes and get a continuous boundary (so you will be able to display the full myelin segmentation (and not only the some outer boundary points).

**Comment by alzaia** [comment]
check issue #9

**Comment by Aymendje** [comment]
Actually, it was already implemented but never used in the test.json
We added a 
      "display":"full"
flag so it would be rendered.
Can you try again ? The git should be up to date now with the correct flag in the default test.json

**Comment by alzaia** [comment]
I tried, but when can I find the display? I dont see any other output image in the output folder, other than the axon-myelin binary result.

**Comment by Aymendje** [comment]
Sorry, it wasnt working probperly.
commit  9e473594f9793487018ee459cad6a1627a4489b0 shoud have fied this issue.
For the output file check test.json
It should be :
            "outputImage":"../tests/SegTest/Step_2_Initial_AxonSeg_mey.png",

**Comment by alzaia** [comment]
Ok, I tested it. But can I also do it for the axons? If I add 'full' to the display in AxonSeg part of json, will I also get the axon display in colors?

**Comment by Zihui-Zhong** [comment]
Like this? http://imgur.com/a/fG1bi

**Comment by alzaia** [comment]
Yes, exactly!

**Comment by alzaia** [comment]
BTW, are you using the 3 discrimination params (minsize, solidity, minormajorraio)? I know theyre on the json file, but not sure if youre using them.

**Comment by Zihui-Zhong** [comment]
THose 3 and the maxSize if it's also present.

**Comment by alzaia** [comment]
Ok good! Theorically, these 4 shouldnt be in the axon segmentation algo part as its mostly axon post-procesing (meaning axons are already segmented, its just like we apply filters to eliminate some of the axons we dont want to keep before launching the myelin step), but its OK, you can leave it like that.

**Comment by Zihui-Zhong** [comment]
Extended minima will generate a lot of noise to be discarded, that's why it is in that step.
![minima](https://cloud.githubusercontent.com/assets/5010555/24940386/ca69b9e0-1f10-11e7-9e43-0829dd76cbeb.png)
