### ISSUE TITLE
Axon segmentation algo inputs

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonsegpy#25]
I tested the software on some other CARS images. What I dont understand, is that when you run the AxonSeg algo (extended minima) your input parameter should be a threshold. I dont see any threshold in the json file, so I guess its currently a fixed value in your algo. This parameter should be changed in the json file, depending on the image and the user.

**Comment by Zihui-Zhong** [comment]
If a parmeter h is provided in the axonSeg parameters, it will be used. If not, a default value = to the standard deviation of the image pixel intensity will be instead.
