### ISSUE TITLE
Terminology issues in the code

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axonsegpy#4]
- class Axone -> Axon (anglais = axon, francais = axone)
- meylin dans code -> myelin (anglais = myelin, francais = myéline)

- noms dans les méthodes et attributs doivent être intuitifs le plus possible ( ex: addAxon, removeAxon, displayAxonlist, ...).

**Comment by jcohenadad** [comment]
hi all, from now on, can you please post all issues in English. Thanks

**Comment by HadrienPerrineau** [comment]
Should be done now.
